// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Alignment
List Alignment(NumericVector input_vec, NumericVector ref_vec);
RcppExport SEXP _TRex_Alignment(SEXP input_vecSEXP, SEXP ref_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type input_vec(input_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ref_vec(ref_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(Alignment(input_vec, ref_vec));
    return rcpp_result_gen;
END_RCPP
}
// Main_Function
List Main_Function(int MaxIter, arma::vec xct, arma::vec nct, arma::vec tr_labels, bool display_progress);
RcppExport SEXP _TRex_Main_Function(SEXP MaxIterSEXP, SEXP xctSEXP, SEXP nctSEXP, SEXP tr_labelsSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type MaxIter(MaxIterSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xct(xctSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nct(nctSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tr_labels(tr_labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(Main_Function(MaxIter, xct, nct, tr_labels, display_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TRex_Alignment", (DL_FUNC) &_TRex_Alignment, 2},
    {"_TRex_Main_Function", (DL_FUNC) &_TRex_Main_Function, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_TRex(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
